### ISSUE TITLE
Unable to filter by Industry for Feb 2022

### ISSUE THREAD

**Issue by vijaya-lakshmi-venkatraman** [epam/OSCI#118]
Clicking on Industry to filter does not display any options.
Note: It works for Jan 2022.

**Comment by mattwynne** [comment]
I just don't see Feb in the drop-down at all:

<img width="816" alt="Screenshot 2022-03-24 at 12 07 28 PM" src="https://user-images.githubusercontent.com/19260/159992083-a56dfc1c-7844-487c-b1b7-0ca55acc9f0f.png">

It does appear very briefly when the page loads, then it disappears.

**Comment by vijaya-lakshmi-venkatraman** [comment]
I am unable to reproduce the issue now
It works fine - the filter works for Feb 2022

**Comment by anausa4eva** [comment]
Hi @vijaya-lakshmi-venkatraman, 
Issue was fixed. Thanks for noticing!
