### ISSUE TITLE
Query on ranking

### ISSUE THREAD

**Issue by vijaya-lakshmi-venkatraman** [epam/OSCI#119]
Hello,
My organization (Societe Generale) as on Feb 2022 seems to have total community number as 7 (+5) and 0 active contributors. Also it is indicated that we are down by 3 places.
I'd like to know why we are placed at 284 and not 276?

When the no of active contributors are equal, what are considered while ranking?
Please can you help with this query?

**Comment by cm-howard** [comment]
![image](https://user-images.githubusercontent.com/71087272/157214760-ae647144-2eb4-4e8b-8a79-d73e9c457c63.png)

**Comment by vijaya-lakshmi-venkatraman** [comment]
Hello @cm-howard ,
Please can you help me with the query?

**Comment by cm-howard** [comment]
Thanks @vijaya-lakshmi-venkatraman - @vlad-isayko is looking into this at the moment and we'll aim to get a response to you soon that explains the logic a little better.

**Comment by anausa4eva** [comment]
Hey @vijaya-lakshmi-venkatraman, 
Let me step in here. At the moment there is no rule for the system to rank all organizations by total community number when number of active contributors is equal for several organizations. And we agree that this rule is logical and should be implemented, so we decided to improve this part with the future system release. As soon as this change will be implemented, I'll let you know.
