### ISSUE TITLE
SmartBear not appearing in the list

### ISSUE THREAD

**Issue by mattwynne** [epam/OSCI#123]
As mentioned in #122, I'm puzzled why SmartBear does not appear in the list, now that we're into the month of April.

We were added in we were added in [v2022.03.0](https://github.com/epam/OSCI/commit/d8f59b4b5722136a2980e2c516bd61eeb08bf611).

I'm not sure if this is user error on my part, so please let me know if there's something I'm misunderstanding, or we need to make some additional configuration.

Here's an example of a commit that I think should have been counted: https://github.com/cucumber/cucumber-js/commits/d98c6deabd39e1adb8e52a1a65324662143108e8

**Comment by DavidGregory084** [comment]
I was also expecting to see @opencastsoftware in the list - see e.g. https://github.com/sbt/sbt/pull/6856/commits/dd497063e5fb41c655f0d18c186b4ef68f215d0b and https://github.com/typelevel/sbt-typelevel/pull/207/commits/309f723dd9ec89a8403eae593ce8887cfbf2c610.

Could this possibly be due to GitHub's email privacy settings?

<img width="785" alt="image" src="https://user-images.githubusercontent.com/2992938/161635637-344ad2c3-bdd9-4269-84fa-c47e01b82499.png">

**Comment by mattwynne** [comment]
> Could this possibly be due to GitHub's email privacy settings?

I wondered that, but that commit I referenced has the full email in the `git log`

**Comment by cm-howard** [comment]
Thanks for the detail on this @mattwynne & @DavidGregory084 it does look a little odd so we're going to investigate this.

Commits do need to be made from the Org domain so using the keep my email private feature, for web based commits, would impact this. However, as you say the full email is visible in the git log. 😟 

@vlad-isayko will have a look into this and we'll feedback asap.

**Comment by anausa4eva** [comment]
Hey @mattwynne & @DavidGregory084 - I'm happy to share good news with you!
Issue with missing companies in the report has been fixed, and now both Smart Bear and Opencast Software are in the OSCI ranking starting from April, 1st. Please check both Monthly and Daily widgets:
![image](https://user-images.githubusercontent.com/94456277/166902974-652f7b8f-eec4-475b-8436-fde1b3ea3d35.png)
![image](https://user-images.githubusercontent.com/94456277/166907665-f944eee3-29a7-42fb-8d68-bb01c2b87cd7.png)

**Comment by DavidGregory084** [comment]
That's perfect, thanks @anausa4eva!

**Comment by mattwynne** [comment]
Great, thanks for closing the loop!
