### ISSUE TITLE
Looking to obtain data in csv format

### ISSUE THREAD

**Issue by reshamas** [epam/OSCI#124]
I am collaborating with Duane O'Brien on a [Digital Infrastructure Project](https://digitalinfrastructure.fund/projects/) called "[Fostering Open Collaboration](https://digitalinfrastructure.fund/projects/fostering-open-collaboration)" (FOCUSED) which is researching open source program offices within companies.  

I would like to access the data on the [Open Source Contributor Index](https://opensourceindex.io/) (OSCI) website.
Source GitHub repo: https://github.com/epam/OSCI

I am looking for guidance on how to obtain it, or a link to the data that appears there, as a .CSV file.

Thank you. 

cc:  @DuaneOBrien

**Comment by cm-howard** [comment]
Thanks for reaching out on this @reshamas and I've followed up with you via email.

For anyone else looking in on this issue we collated the data for OSCI into a series of files that are available for all to be downloaded here: https://ststaticprodosciwebz2vmu.blob.core.windows.net/data/share/OSCI_change_ranking.zip 

These are accurate as of April 11th 2022.
