### ISSUE TITLE
Clarification counting method

### ISSUE THREAD

**Issue by OhItsLena** [epam/OSCI#129]
Am I right in assuming that these are the steps you take to count the open source contributions?
1. get commits from push event data (GH Archive/BigQuery)
2. only keep commits to repositories, which do have a license (GitHub API for license info)
3. match author email domains for selected organizations
4. use the author email to identify unique contributors and count commits
5. count total community / active contributors

I just wanted to clarify so I better understand how to interpret the results. Great project.

**Comment by vlad-isayko** [comment]
Yes, @OhItsLena ,you are absolutely right in general, this is exactly the logic that is laid down. Unless the order of actions is different: steps 2 and 3 need to be swapped.

**Comment by OhItsLena** [comment]
Absolutely makes sense from a data processing standpoint. Thanks for clarifying @vlad-isayko!
