### ISSUE TITLE
How to obtain country name for the records in the dataset

### ISSUE THREAD

**Issue by reshamas** [epam/OSCI#131]
Hello,
I was looking for the country that the OSCI company would be headquartered in.  
Would you know what's the best way to obtain this information?

Thank you.

>For anyone else looking in on this issue we collated the data for OSCI into a series of files that are available for all to be downloaded here: https://ststaticprodosciwebz2vmu.blob.core.windows.net/data/share/OSCI_change_ranking.zip

cc: @DuaneOBrien

**Comment by vlad-isayko** [comment]
Do you mean how to get countries for companies participating in the OSCI ranking?

We did not have such functionality. But I think that for most companies you can get information, for example, from Wikipedia. But not all may be there.

For research purposes, I would suggest trying to automatically collect information from Wikipedia, the rest can be obtained, I think, manually.

**Comment by reshamas** [comment]
Thanks @vlad-isayko
