### ISSUE TITLE
License clarity

### ISSUE THREAD

**Issue by abitrolly** [epam/OSCI#14]
Looks like some files in this repo were copied from Mypy project (https://github.com/epam/OSCI/commit/471ccc3ca34e40d26c5cc29f3e80d8c3d0e8f39a). It would be nice to see that Epam actually fulfilled all License obligations towards open source projects it is using, giving proper credits where due.

**Comment by patrickstephens1** [comment]
Closing this. We reused some lines of text when we created the CONTRIBUTING.md, nothing more. The mypy is already replaced.

**Comment by abitrolly** [comment]
@patrickstephens1 are there any tools you are using at Epam to ensure legal clarity for other code as well?

**Comment by patrickstephens1** [comment]
Black Duck Protex is used as part of our process
