### ISSUE TITLE
Sponsorship clarity

### ISSUE THREAD

**Issue by abitrolly** [epam/OSCI#15]
In this paragraph - https://github.com/epam/OSCI#where-can-i-see-the-latest-rankings

> This project is sponsored by EPAM Systems and the latest results are visible on the EPAM SolutionsHub OSCI page. 

It is better to clarify that no sponsorship is available to outside contributors.

**Comment by irynastr** [comment]
Hi Anatoliy. Thanks for raising this issue, I have changed the text in [README](https://github.com/epam/OSCI#where-can-i-see-the-latest-rankings) so that it's clear.

**Comment by abitrolly** [comment]
@irynastr yes, a73824a48315d6af9159ca9a2021b2c7a4fc8e5a makes it clear. Thanks. )
