### ISSUE TITLE
OSCI shows wrong count of ACTIVE CONTRIBUTORS in yearly date

### ISSUE THREAD

**Issue by RHillesheim** [epam/OSCI#58]
When the YEARLY data is chosen, the list shows the same number of ACTIVE CONTRIBUTORS and TOTAL COMMUNITY per year and company then for January of the same year. Therefor the data seems to be wrong and at least the ranking by year could be inaccurate. 
Could this problem be fixed?

**Comment by vlad-isayko** [comment]
Thank you very much for your helpful comment.

We really missed this bug. But we have already fixed everything and you can verify this by reloading the page with clearing the cache.

If you have questions and comments, you can reopen or create a new issue
